@startuml Dynamics Data Management
!include <archimate/Archimate>

' Motivational Stakeholder
Motivation_Stakeholder(vibrationEngineer, "Vibration\nEngineer")

' Business Service
Business_Service(rawDynamicDataProcessing, "Raw Dynamic Data Processing")

' Business Function
Business_Function(dataManagement, "Data\nManagement")

' Business Process
Business_Process(import, "Import")
Business_Process(analyse, "Analyse")
Business_Process(export, "Export")
Business_Process(remove, "Remove")


' Application Services
Application_Service(importService, "Import\nService")

Application_Service(exportForFdmIngestionService, "Exporting for\nFDM Azure\nIngestion")
Application_Service(uploadToAzureService, "Uploading to\nFDM Azure")
Application_Service(fdmAzureIngestionService, "Calling\nFDM Azure\nIngestion\nService")
Application_Service(deleteService, "Delete\nService")

' Applications Components
Application_Component(dynamicsTlsImporter, "dynamics_tls_importer")
Application_Component(dynamicsFdmExporter, "dynamics_fdm_exporter")
Application_Component(dynamicsDelete, "dynamics_delete")
Application_Component(postUrlIngest, "post_url_ingest")
Application_Component(fdmIngestPending, "fdm_ingest_pending")

' Application Functions
Application_Function(importFunction, "Import\nFunction")
Application_Function(fdmOutputFunction, "FDM\nOutput\nFunction")
Application_Function(deleteFunction, "Delete\nFunction")

' Technology_
Technology_Service(dataMovementService, "FileCatalyst\nHotFolder\nService")

' Relations
Rel_Realization_Up(dataManagement, rawDynamicDataProcessing)
Rel_Realization_Up(importFunction, importService)
Rel_Realization_Up(deleteFunction, deleteService)
Rel_Realization_Up(fdmOutputFunction, exportForFdmIngestionService)
Rel_Aggregation(dataManagement, import)
Rel_Aggregation(dataManagement, export)
Rel_Aggregation(dataManagement, remove)
Rel_Serving_Up(importService, import)
Rel_Serving_Up(deleteService, remove)
Rel_Serving_Up(uploadToAzureService, export)
Rel_Serving_Up(fdmAzureIngestionService, export)
Rel_Serving_Up(exportForFdmIngestionService, export)
Rel_Serving_Up(dataMovementService, uploadToAzureService)
Rel_Composition_Up(dynamicsTlsImporter, importFunction)
Rel_Composition_Up(dynamicsFdmExporter, fdmOutputFunction)
Rel_Composition_Up(dynamicsDelete, deleteFunction)


@enduml