@startuml Dynamics Data Management
!include <archimate/Archimate>

' Business
Business_Location(derbyCampus, "Derby\nCampus")

' Physical
Physical_Facility(testBed80, "Test Bed 80")
Physical_Facility(controlRoom, "Control\nRoom")
Physical_Facility(equipmentRoom, "Equipment\nRoom")

Rel_Aggregation(derbyCampus, testBed80)
Rel_Aggregation(testBed80, controlRoom)
Rel_Aggregation(testBed80, equipmentRoom)